# Generated by Django 5.2.3 on 2025-06-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_studentuser_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bewerbung",
            old_name="eingereicht_am",
            new_name="erstellt_am",
        ),
        migrations.AddField(
            model_name="bewerbung",
            name="abschluss",
            field=models.CharField(
                choices=[("bachelor", "Bachelor"), ("master", "Master")],
                default="bachelor",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bewerbung",
            name="datei",
            field=models.FileField(blank=True, null=True, upload_to="bewerbungen/"),
        ),
        migrations.AddField(
            model_name="bewerbung",
            name="form",
            field=models.CharField(
                choices=[("online", "Online"), ("praesenz", "Präsenz")],
                default="online",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bewerbung",
            name="sprachen",
            field=models.CharField(default="Deutsch", max_length=100),
        ),
        migrations.AddField(
            model_name="bewerbung",
            name="voraussetzungen",
            field=models.TextField(default="Keine Angabe"),
        ),
        migrations.AlterField(
            model_name="bewerbung",
            name="studiengang",
            field=models.CharField(
                choices=[
                    ("inf", "Informatik"),
                    ("wiwi", "Wirtschaftswissenschaften"),
                    ("med", "Medizin"),
                ],
                default="inf",
                max_length=20,
            ),
        ),
    ]
