# Generated by Django 5.2.3 on 2025-06-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0003_rename_eingereicht_am_bewerbung_erstellt_am_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bewerbung",
            name="status",
            field=models.CharField(
                choices=[
                    ("neu", "Neu"),
                    ("angenommen", "Angenommen"),
                    ("abgelehnt", "Abgelehnt"),
                ],
                default="neu",
                max_length=20,
            ),
        ),
    ]
