# Generated by Django 5.2.3 on 2025-06-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0005_bewerbung_benutzer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bewerbung",
            name="voraussetzungen",
        ),
        migrations.AddField(
            model_name="bewerbung",
            name="land",
            field=models.CharField(default="Deutschland", max_length=50),
        ),
        migrations.AddField(
            model_name="bewerbung",
            name="ort",
            field=models.CharField(default="Unbekannt", max_length=50),
        ),
        migrations.AddField(
            model_name="bewerbung",
            name="plz",
            field=models.CharField(default="00000", max_length=10),
        ),
        migrations.AddField(
            model_name="bewerbung",
            name="strasse",
            field=models.CharField(default="Unbekannt", max_length=100),
        ),
        migrations.AlterField(
            model_name="bewerbung",
            name="studiengang",
            field=models.CharField(
                choices=[
                    ("medieninf", "Medieninformatik"),
                    ("data_sci", "Data Science"),
                    ("ai", "Künstliche Intelligenz"),
                    ("swt", "Softwaretechnik"),
                    ("bwl", "Betriebswirtschaft"),
                    ("vw", "Volkswirtschaft"),
                    ("ibwl", "Internationale BWL"),
                    ("wi_info", "Wirtschaftsinformatik"),
                    ("humanmed", "Humanmedizin"),
                    ("zahnmed", "Zahnmedizin"),
                    ("medizintech", "Medizintechnik"),
                ],
                default="inf",
                max_length=20,
            ),
        ),
    ]
